### ISSUE TITLE
Convention for (math) fonts in ZIPs

### ISSUE THREAD

**Issue by AntoineRondelet** [QED-it/zips#25]
See: https://github.com/QED-it/zips/pull/20#issuecomment-1575517341

In ZIP227 we use different types of fonts:
- `mathsf`
- Single backticks \`variable\`
- Double backticks \`\`variable\`\`

It isn't very clear to me what these represent.
@vivek-arte proposed an answer here: https://github.com/QED-it/zips/pull/20#issuecomment-1566767851

But, then I am wondering: maybe we should also change all instances of things like `\mathsf{assetDescSize}` into \`\`assetDescSize\`\` (outside of equations) since we use assetDescSize in the Issuance Action Description Table.

Likewise, why do we use simple backticks on things like `notes`, `NoteCommitmentTree`, `issueAuthSig` etc etc? For instance, `issueAuthSig` is in the Issuance Bundle table, yet, we use single backticks (\`) around it, no double. Same for \`\`finalize\`\`: it's "just" the LSB of `flagIssuance` and so it isn't an entry of the Issuance Action Description in itself, so the double ticks should be used for the flagIssuance, really, not for the finalize bit.

AFAICT, there are some of these inconsistencies in other ZIPs as well, for instance:
- ZIP-0239, ZIP-0032 uses \`zcashd\`
- ZIP-0173 uses \`\`zcashd\`\`

If would be nice to clarify this to draw a clear link between font and "purpose", else this is more confusing than it helps.

**Comment by vivek-arte** [comment]
The changes in [PR#28](https://github.com/QED-it/zips/pull/28) make some of the changes along these lines. 

However, Daira has [commented](https://github.com/zcash/zips/pull/680#discussion_r1224995304) on the changes making the convention more explicit. 

So, one more pass is necessary to make sure we are consistent with that comment (and especially reverting my change to `isk` in PR#28).

**Comment by vivek-arte** [comment]
We have made the change to the convention as linked in the earlier comment, closing this issue for now.
